/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import calculadora.Calculadora;
import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.util.Arrays;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 * <a rel="license" href="
 * http://creativecommons.org/licenses/by-nc-nd/3.0/deed.es"><img alt="Licencia
 * Creative Commons" style="border-width:0" src="
 * http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png" /></a><br /><span xmln
 * s:dct="http://purl.org/dc/terms/" property="dct:title">Calculadora</span> por
 * <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName"
 * >Andrés Sarmiento Tobón</span> se encuentra bajo una <a rel="license" href="
 * http://creativecommons.org/licenses/by-nc-nd/3.0/deed.es">Licencia Creative
 * Commons Atribución-NoComercial-SinDerivadas 3.0 Unported</a>
 * <p/>
 * @author Andrés Sarmiento Tobón <href>ansarmientoto@unal.edu.co</href>
 */
public class SelectorColor extends javax.swing.JFrame {

    private static final long serialVersionUID = -100L;
    private boolean aceptado = false;

    /**
     * Creates new form SelectorColor
     */
    public SelectorColor() {
        initComponents();

        try {
            setIconImage(ImageIO.read(getClass().getResource(
                    "/gui/selectcolor.png")));
        } catch (IOException ex) {
            Logger.getLogger(VentanaCalculo.class.getName()).log(Level.SEVERE,
                    null, ex);
        } finally {
            setLocationRelativeTo(Calculadora.getPreferencias());
            actualizar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jColorChooser1 = new javax.swing.JColorChooser();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setTitle("Seleccione el color");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                salirSelectorColor(evt);
            }
        });

        jPanel1.setBackground(VentanaCalculo.COLOR_FONDO_PREDETERMINADO);
        jPanel1.setForeground(VentanaCalculo.COLOR_FUENTE_PREDETERMINADO);
        jPanel1.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N

        jColorChooser1.setBackground(VentanaCalculo.COLOR_FONDO_PREDETERMINADO);
        jColorChooser1.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jColorChooser1.setForeground(VentanaCalculo.COLOR_FUENTE_PREDETERMINADO);
        jColorChooser1.setMaximumSize(new java.awt.Dimension(821, 483));
        jColorChooser1.setMinimumSize(new java.awt.Dimension(821, 483));
        jColorChooser1.setOpaque(false);
        jColorChooser1.setPreferredSize(new java.awt.Dimension(821, 483));

        jButton10.setBackground(VentanaCalculo.COLOR_BOTON_PREDETERMINADO);
        jButton10.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jButton10.setText("Cancelar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelar(evt);
            }
        });

        jButton9.setBackground(VentanaCalculo.COLOR_BOTON_PREDETERMINADO);
        jButton9.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jButton9.setText("Aceptar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptar(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButton9)
                .addGap(192, 192, 192)
                .addComponent(jButton10)
                .addContainerGap())
            .addComponent(jColorChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void botonCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelar
        setVisible(false);
        salir();
    }//GEN-LAST:event_botonCancelar

    /**
     *
     * @param evt
     */
    private void botonAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptar
        setVisible(false);
        aceptado = true;
        Calculadora.getPreferencias().setVisible(true);
        actualizar();
    }//GEN-LAST:event_botonAceptar

    /**
     *
     * @param evt
     */
    private void salirSelectorColor(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_salirSelectorColor
        salir();
    }//GEN-LAST:event_salirSelectorColor

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculadora.getSelectorColor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void actualizar() {
        //        AbstractColorChooserPanel[] paneles = jColorChooser1.getChooserPanels();
        //        for (AbstractColorChooserPanel abstractColorChooserPanel : paneles) {
        //            abstractColorChooserPanel.setBackground(Preferencias.getColorFondo());
        //        }

        Queue<java.awt.Component> cola = new java.util.LinkedList<>(Arrays
                .asList(jColorChooser1.getComponents()));

        while (!cola.isEmpty()) {
            java.awt.Component componente = cola.poll();

            componente.setFont(new java.awt.Font("Ubuntu Light", 0, 24));

            if (componente instanceof java.awt.Container) {
                cola.addAll(Arrays.asList(((java.awt.Container) componente)
                        .getComponents()));
            }

            if (componente instanceof java.awt.Button ||
                    componente instanceof javax.swing.JButton) {
                componente.setBackground(Preferencias.getColorBoton());
            } else if (componente instanceof java.awt.Panel ||
                    componente instanceof javax.swing.JPanel) {
                componente.setBackground(Preferencias.getColorFondo());
            }
        }

        repaint();

    }

    /**
     *
     * @return
     */
    public Color getColor() {
        return jColorChooser1.getColor();
    }

    /**
     *
     * @param color
     */
    public void setColor(Color color) {
        jColorChooser1.setColor(color);
    }

    /**
     *
     * @return
     */
    public boolean isAceptado() {
        return aceptado;
    }

    /**
     *
     * @param aceptado
     */
    public void setAceptado(boolean aceptado) {
        this.aceptado = aceptado;
    }

    @Override
    public void setVisible(boolean b) {
        
        if (b) {
            setLocationRelativeTo(calculadora.Calculadora.getPreferencias());
            this.toFront();
        }

        repaint();
        super.setVisible(b);
    }

    /**
     * 
     */
    private void salir() {
        aceptado = false;
        Calculadora.getPreferencias().setVisible(true);
    }
}
